version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build: 
      context: ./PlanCalculator
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always 
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development